# Generated by Django 5.2.12 on 2026-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blitzcontestconfig',
            name='intermission_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Ile przerwy po solvie.', verbose_name='przerwa'),
        ),
    ]
