# Generated by Django 5.2.12 on 2026-04-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_probleminstance_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probleminstance',
            options={'ordering': ('round', 'order', 'short_name'), 'verbose_name': 'problem instance', 'verbose_name_plural': 'problem instances'},
        ),
    ]
