# Generated by Django 4.2.20 on 2026-04-13 12:30

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0026_alter_probleminstance_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemScoreDisplayConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score_mode",
                    oioioi.base.fields.EnumField(
                        default="last",
                        help_text="Determines whether the Problems page shows the last or the best visible submission score.",
                        max_length=64,
                        verbose_name="problems score mode",
                    ),
                ),
                ("contest", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="contests.contest")),
            ],
            options={
                "verbose_name": "problem score display config",
                "verbose_name_plural": "problem score display configs",
            },
        ),
    ]
