# Generated by Django 4.2.20 on 2026-04-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0027_problemscoredisplayconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="post_end_submission_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, participants may continue submitting after the round ends until this time.",
                null=True,
                verbose_name="post-end submissions until",
            ),
        ),
    ]
