# Generated by Django 4.2.20 on 2026-04-15 20:30

from django.db import migrations, models
import django.db.models.deletion
import oioioi.contests.models
import oioioi.filetracker.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0028_round_post_end_submission_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemEditorial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content",
                    oioioi.filetracker.fields.FileField(
                        upload_to=oioioi.contests.models.make_problem_editorial_filename,
                        validators=[oioioi.contests.models.validate_pdf_file],
                        verbose_name="content",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="publication date"),
                ),
                (
                    "problem_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial",
                        to="contests.probleminstance",
                        verbose_name="problem instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "problem editorial",
                "verbose_name_plural": "problem editorials",
            },
        ),
    ]
