# Generated by Django 4.2.20 on 2026-04-13 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0026_alter_probleminstance_options"),
        ("rankings", "0004_rankingmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurableRanking",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("medal_scheme", oioioi.base.fields.EnumField(default="none", max_length=64, verbose_name="medal scheme")),
                ("show_sum", models.BooleanField(default=True, verbose_name="show sum")),
                ("show_percentage", models.BooleanField(default=False, verbose_name="show percentage")),
                ("show_difference", models.BooleanField(default=False, verbose_name="show leader difference")),
                ("contest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="configurable_rankings", to="contests.contest")),
            ],
            options={
                "verbose_name": "configurable ranking",
                "verbose_name_plural": "configurable rankings",
                "ordering": ("contest", "order", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="ConfigurableRankingRound",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("coefficient", models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="coefficient")),
                ("score_mode", oioioi.base.fields.EnumField(default="best", max_length=64, verbose_name="score mode")),
                ("column_visibility", oioioi.base.fields.EnumField(default="after_results", max_length=64, verbose_name="column visibility")),
                ("ignore_submissions_after", models.DateTimeField(blank=True, null=True, verbose_name="ignore submissions after")),
                ("ranking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="round_configs", to="rankings.configurableranking", verbose_name="ranking")),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contests.round", verbose_name="round")),
            ],
            options={
                "verbose_name": "configurable ranking round",
                "verbose_name_plural": "configurable ranking rounds",
                "ordering": ("ranking", "order", "round__start_date", "round__name", "id"),
                "unique_together": {("ranking", "round")},
            },
        ),
    ]
