# Generated by Django 4.2.20 on 2026-04-13 13:45

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0027_problemscoredisplayconfig"),
        ("rankings", "0005_configurableranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurableRankingSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "show_default_rankings",
                    models.BooleanField(
                        default=True,
                        help_text="Determines whether the built-in contest and round rankings remain visible alongside configurable ones.",
                        verbose_name="show default rankings",
                    ),
                ),
                ("contest", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="contests.contest")),
            ],
            options={
                "verbose_name": "configurable ranking settings",
                "verbose_name_plural": "configurable ranking settings",
            },
        ),
        migrations.AddField(
            model_name="configurablerankinground",
            name="all_time_coefficient",
            field=models.IntegerField(default=0, verbose_name="all-time coefficient"),
        ),
        migrations.AddField(
            model_name="configurablerankinground",
            name="all_time_score_mode",
            field=oioioi.base.fields.EnumField(default="best", max_length=64, verbose_name="all-time score mode"),
        ),
        migrations.AddField(
            model_name="configurablerankinground",
            name="source_type",
            field=oioioi.base.fields.EnumField(default="round", max_length=64, verbose_name="source type"),
        ),
        migrations.AddField(
            model_name="configurablerankinground",
            name="sub_ranking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referencing_round_configs",
                to="rankings.configurableranking",
                verbose_name="sub-ranking",
            ),
        ),
        migrations.AlterField(
            model_name="configurablerankinground",
            name="coefficient",
            field=models.IntegerField(default=1, verbose_name="coefficient"),
        ),
        migrations.AlterField(
            model_name="configurablerankinground",
            name="round",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="contests.round", verbose_name="round"),
        ),
        migrations.AlterModelOptions(
            name="configurablerankinground",
            options={
                "ordering": ("ranking", "order", "id"),
                "verbose_name": "configurable ranking source",
                "verbose_name_plural": "configurable ranking sources",
            },
        ),
        migrations.AlterUniqueTogether(
            name="configurablerankinground",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="configurablerankinground",
            constraint=models.UniqueConstraint(
                condition=models.Q(round__isnull=False),
                fields=("ranking", "round"),
                name="rankings_unique_round_source_per_ranking",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurablerankinground",
            constraint=models.UniqueConstraint(
                condition=models.Q(sub_ranking__isnull=False),
                fields=("ranking", "sub_ranking"),
                name="rankings_unique_subranking_source_per_ranking",
            ),
        ),
    ]
